name: build docs

on:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -p "${{ secrets.SSH_PORT || '22' }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Rebase on master and build docs (remote)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          set -euo pipefail
          ssh -o StrictHostKeyChecking=yes -p "${SSH_PORT:-22}" "$SSH_USER@$SSH_HOST" <<'EOF'
          set -e
          REPO_DIR="$HOME/github/ineoo/meeting-selector"
          test -d "$REPO_DIR/.git" || { echo "Repo not found at $REPO_DIR"; exit 2; }
          cd "$REPO_DIR"
          git pull --rebase origin master
          pnpm install --no-frozen-lockfile
          pnpm run build:react-meeting-selector
          pnpm run build:vue-meeting-selector
          pnpm run build:docs
          EOF
