name: Publish vue package

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to pull'
        required: true
        default: 'master'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - uses: pnpm/action-setup@v4

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build:vue-meeting-selector

      - name: Publish
        working-directory: packages/vue-meeting-selector
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VUE_NPM_TOKEN }}
        run: npm publish --access public
