name: Publish react package
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to pull'
        required: true
        default: 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build:react-meeting-selector
      - name: Publish
        run: |
          cd packages/react-meeting-selector
          npm publish
